### ISSUE TITLE
Is a user of the CLI I would like to download a  well log using the OSDU core API

### ISSUE THREAD

**Issue by josmiseth** [equinor/osdu-cli#11]
Starting from a query for OSDU work product component WellLog and a specific Well ID, I would like to download the well logs for that well ID.

**Comment by mahewitt** [comment]
Support for downloading from the file service is added. Will look into being able to download directly from a WPC id - https://community.opengroup.org/osdu/platform/data-flow/data-loading/osdu-cli/-/issues/9
